export const COLLECTIONS = {
  USERS: 'janakural_users',
  ISSUES: 'janakural_issues',
  ISSUE_HISTORY: 'janakural_issue_history',
  STATES: 'janakural_states',
  CATEGORIES: 'janakural_categories',
  ANALYTICS: 'janakural_analytics',
  NOTIFICATIONS: 'janakural_notifications',
} as const;

export const STORAGE_PATHS = {
  ROOT: 'janakural',
  ISSUES: 'janakural/issues',
  PROFILES: 'janakural/profiles',
  TEMP: 'janakural/temp',
} as const;

export const CATEGORIES = [
  { id: 'road', name: 'சாலை பிரச்சனைகள்', nameEn: 'Road Issues', icon: '🛣️', color: 'bg-orange-100 text-orange-600' },
  { id: 'water', name: 'குடிநீர்', nameEn: 'Water Supply', icon: '💧', color: 'bg-blue-100 text-blue-600' },
  { id: 'electricity', name: 'மின்சாரம்', nameEn: 'Electricity', icon: '⚡', color: 'bg-yellow-100 text-yellow-600' },
  { id: 'sanitation', name: 'சுகாதாரம்', nameEn: 'Sanitation', icon: '🧹', color: 'bg-green-100 text-green-600' },
  { id: 'drainage', name: 'வடிகால்', nameEn: 'Drainage', icon: '🌊', color: 'bg-purple-100 text-purple-600' },
  { id: 'streetlight', name: 'தெரு விளக்கு', nameEn: 'Street Light', icon: '💡', color: 'bg-amber-100 text-amber-600' },
];

export const getIssuePhotoPath = (issueId: string, fileName: string) =>
  `${STORAGE_PATHS.ISSUES}/${issueId}/${fileName}`;

export const getProfilePhotoPath = (userId: string, fileName: string) =>
  `${STORAGE_PATHS.PROFILES}/${userId}/${fileName}`;

// Tamil Nadu Districts
export const DISTRICTS = [
  { id: 'ariyalur', name: 'அரியலூர்', nameEn: 'Ariyalur' },
  { id: 'chengalpattu', name: 'செங்கல்பட்டு', nameEn: 'Chengalpattu' },
  { id: 'chennai', name: 'சென்னை', nameEn: 'Chennai' },
  { id: 'coimbatore', name: 'கோயம்புத்தூர்', nameEn: 'Coimbatore' },
  { id: 'cuddalore', name: 'கடலூர்', nameEn: 'Cuddalore' },
  { id: 'dharmapuri', name: 'தர்மபுரி', nameEn: 'Dharmapuri' },
  { id: 'dindigul', name: 'திண்டுக்கல்', nameEn: 'Dindigul' },
  { id: 'erode', name: 'ஈரோடு', nameEn: 'Erode' },
  { id: 'kallakurichi', name: 'கள்ளக்குறிச்சி', nameEn: 'Kallakurichi' },
  { id: 'kancheepuram', name: 'காஞ்சிபுரம்', nameEn: 'Kancheepuram' },
  { id: 'kanyakumari', name: 'கன்னியாகுமரி', nameEn: 'Kanyakumari' },
  { id: 'karur', name: 'கரூர்', nameEn: 'Karur' },
  { id: 'krishnagiri', name: 'கிருஷ்ணகிரி', nameEn: 'Krishnagiri' },
  { id: 'madurai', name: 'மதுரை', nameEn: 'Madurai' },
  { id: 'mayiladuthurai', name: 'மயிலாடுதுறை', nameEn: 'Mayiladuthurai' },
  { id: 'nagapattinam', name: 'நாகப்பட்டினம்', nameEn: 'Nagapattinam' },
  { id: 'namakkal', name: 'நாமக்கல்', nameEn: 'Namakkal' },
  { id: 'nilgiris', name: 'நீலகிரி', nameEn: 'Nilgiris' },
  { id: 'perambalur', name: 'பெரம்பலூர்', nameEn: 'Perambalur' },
  { id: 'pudukkottai', name: 'புதுக்கோட்டை', nameEn: 'Pudukkottai' },
  { id: 'ramanathapuram', name: 'ராமநாதபுரம்', nameEn: 'Ramanathapuram' },
  { id: 'ranipet', name: 'ராணிப்பேட்டை', nameEn: 'Ranipet' },
  { id: 'salem', name: 'சேலம்', nameEn: 'Salem' },
  { id: 'sivaganga', name: 'சிவகங்கை', nameEn: 'Sivaganga' },
  { id: 'tenkasi', name: 'தென்காசி', nameEn: 'Tenkasi' },
  { id: 'thanjavur', name: 'தஞ்சாவூர்', nameEn: 'Thanjavur' },
  { id: 'theni', name: 'தேனி', nameEn: 'Theni' },
  { id: 'thoothukudi', name: 'தூத்துக்குடி', nameEn: 'Thoothukudi' },
  { id: 'tiruchirappalli', name: 'திருச்சிராப்பள்ளி', nameEn: 'Tiruchirappalli' },
  { id: 'tirunelveli', name: 'திருநெல்வேலி', nameEn: 'Tirunelveli' },
  { id: 'tirupathur', name: 'திருப்பத்தூர்', nameEn: 'Tirupathur' },
  { id: 'tiruppur', name: 'திருப்பூர்', nameEn: 'Tiruppur' },
  { id: 'tiruvallur', name: 'திருவள்ளூர்', nameEn: 'Tiruvallur' },
  { id: 'tiruvannamalai', name: 'திருவண்ணாமலை', nameEn: 'Tiruvannamalai' },
  { id: 'tiruvarur', name: 'திருவாரூர்', nameEn: 'Tiruvarur' },
  { id: 'vellore', name: 'வேலூர்', nameEn: 'Vellore' },
  { id: 'viluppuram', name: 'விழுப்புரம்', nameEn: 'Viluppuram' },
  { id: 'virudhunagar', name: 'விருதுநகர்', nameEn: 'Virudhunagar' },
];

// Panchayat Unions by District (all 38 Tamil Nadu districts)
export const PANCHAYAT_UNIONS: Record<string, { id: string; name: string; nameEn: string }[]> = {
  ariyalur: [
    { id: 'ariyalur', name: 'அரியலூர்', nameEn: 'Ariyalur' },
    { id: 'sendurai', name: 'செந்துறை', nameEn: 'Sendurai' },
    { id: 'udayarpalayam', name: 'உடையார்பாளையம்', nameEn: 'Udayarpalayam' },
    { id: 'andimadam', name: 'ஆண்டிமடம்', nameEn: 'Andimadam' },
    { id: 'thirumanur', name: 'திருமானூர்', nameEn: 'Thirumanur' },
    { id: 't_palur', name: 'டி.பாளூர்', nameEn: 'T.Palur' },
  ],
  chengalpattu: [
    { id: 'chengalpattu', name: 'செங்கல்பட்டு', nameEn: 'Chengalpattu' },
    { id: 'thiruporur', name: 'திருப்போரூர்', nameEn: 'Thiruporur' },
    { id: 'maduranthakam', name: 'மதுராந்தகம்', nameEn: 'Maduranthakam' },
    { id: 'kattankolathur', name: 'காட்டான்கொளத்தூர்', nameEn: 'Kattankolathur' },
    { id: 'tirukalukundram', name: 'திருக்கழுக்குன்றம்', nameEn: 'Tirukalukundram' },
    { id: 'lathur', name: 'லத்தூர்', nameEn: 'Lathur' },
    { id: 'tambaram', name: 'தாம்பரம்', nameEn: 'Tambaram' },
    { id: 'vandalur', name: 'வண்டலூர்', nameEn: 'Vandalur' },
  ],
  chennai: [
    { id: 'chennai_corporation', name: 'சென்னை மாநகராட்சி', nameEn: 'Chennai Corporation' },
  ],
  coimbatore: [
    { id: 'coimbatore_north', name: 'கோயம்புத்தூர் வடக்கு', nameEn: 'Coimbatore North' },
    { id: 'coimbatore_south', name: 'கோயம்புத்தூர் தெற்கு', nameEn: 'Coimbatore South' },
    { id: 'sulur', name: 'சூலூர்', nameEn: 'Sulur' },
    { id: 'annur', name: 'அன்னூர்', nameEn: 'Annur' },
    { id: 'karamadai', name: 'கரமடை', nameEn: 'Karamadai' },
    { id: 'mettupalayam', name: 'மேட்டுப்பாளையம்', nameEn: 'Mettupalayam' },
    { id: 'pollachi', name: 'பொள்ளாச்சி', nameEn: 'Pollachi' },
    { id: 'kinathukadavu', name: 'கிணத்துக்கடவு', nameEn: 'Kinathukadavu' },
    { id: 'madukkarai', name: 'மடுக்கரை', nameEn: 'Madukkarai' },
    { id: 'thondamuthur', name: 'தொண்டாமுத்தூர்', nameEn: 'Thondamuthur' },
    { id: 'perur', name: 'பேரூர்', nameEn: 'Perur' },
    { id: 'sarcarsamakulam', name: 'சர்க்கார்சாமக்குளம்', nameEn: 'Sarcarsamakulam' },
  ],
  cuddalore: [
    { id: 'cuddalore', name: 'கடலூர்', nameEn: 'Cuddalore' },
    { id: 'kurinjipadi', name: 'குறிஞ்சிப்பாடி', nameEn: 'Kurinjipadi' },
    { id: 'panruti', name: 'பண்ருட்டி', nameEn: 'Panruti' },
    { id: 'virudhachalam', name: 'விருத்தாசலம்', nameEn: 'Virudhachalam' },
    { id: 'kattumannarkoil', name: 'கட்டுமன்னார்கோயில்', nameEn: 'Kattumannarkoil' },
    { id: 'mangalur', name: 'மங்களூர்', nameEn: 'Mangalur' },
    { id: 'bhuvanagiri', name: 'புவனகிரி', nameEn: 'Bhuvanagiri' },
    { id: 'parangipettai', name: 'பரங்கிப்பேட்டை', nameEn: 'Parangipettai' },
    { id: 'melbhuvanagiri', name: 'மேல்புவனகிரி', nameEn: 'Melbhuvanagiri' },
    { id: 'keerapalayam', name: 'கீரப்பாளையம்', nameEn: 'Keerapalayam' },
    { id: 'annagramam', name: 'அன்னாகிராமம்', nameEn: 'Annagramam' },
    { id: 'kumaratchi', name: 'குமாரச்சி', nameEn: 'Kumaratchi' },
    { id: 'nallur', name: 'நல்லூர்', nameEn: 'Nallur' },
  ],
  dharmapuri: [
    { id: 'dharmapuri', name: 'தர்மபுரி', nameEn: 'Dharmapuri' },
    { id: 'pennagaram', name: 'பென்னாகரம்', nameEn: 'Pennagaram' },
    { id: 'palacode', name: 'பாலக்கோடு', nameEn: 'Palacode' },
    { id: 'karimangalam', name: 'கரிமங்கலம்', nameEn: 'Karimangalam' },
    { id: 'nallampalli', name: 'நல்லம்பள்ளி', nameEn: 'Nallampalli' },
    { id: 'pappireddipatti', name: 'பாப்பிரெட்டிபட்டி', nameEn: 'Pappireddipatti' },
    { id: 'harur', name: 'அரூர்', nameEn: 'Harur' },
    { id: 'morappur', name: 'மொரப்பூர்', nameEn: 'Morappur' },
  ],
  dindigul: [
    { id: 'dindigul', name: 'திண்டுக்கல்', nameEn: 'Dindigul' },
    { id: 'palani', name: 'பழனி', nameEn: 'Palani' },
    { id: 'oddanchatram', name: 'ஒட்டன்சத்திரம்', nameEn: 'Oddanchatram' },
    { id: 'athoor', name: 'ஆத்தூர்', nameEn: 'Athoor' },
    { id: 'kodaikanal', name: 'கொடைக்கானல்', nameEn: 'Kodaikanal' },
    { id: 'nilakottai', name: 'நிலக்கோட்டை', nameEn: 'Nilakottai' },
    { id: 'vadamadurai', name: 'வடமதுரை', nameEn: 'Vadamadurai' },
    { id: 'natham', name: 'நாத்தம்', nameEn: 'Natham' },
    { id: 'vedasandur', name: 'வேடசந்தூர்', nameEn: 'Vedasandur' },
    { id: 'reddiarchatram', name: 'ரெட்டியார்சத்திரம்', nameEn: 'Reddiarchatram' },
    { id: 'shanarpatti', name: 'சனார்பட்டி', nameEn: 'Shanarpatti' },
    { id: 'guziliamparai', name: 'குழித்தலைப்பாறை', nameEn: 'Guziliamparai' },
    { id: 'batlagundu', name: 'பட்டிவீரன்பட்டி', nameEn: 'Batlagundu' },
    { id: 'thoppampatti', name: 'தொப்பம்பட்டி', nameEn: 'Thoppampatti' },
  ],
  erode: [
    { id: 'erode', name: 'ஈரோடு', nameEn: 'Erode' },
    { id: 'gobichettipalayam', name: 'கோபிச்செட்டிப்பாளையம்', nameEn: 'Gobichettipalayam' },
    { id: 'bhavani', name: 'பவானி', nameEn: 'Bhavani' },
    { id: 'sathyamangalam', name: 'சத்தியமங்கலம்', nameEn: 'Sathyamangalam' },
    { id: 'perundurai', name: 'பெருந்துறை', nameEn: 'Perundurai' },
    { id: 'modakurichi', name: 'மோடக்குறிச்சி', nameEn: 'Modakurichi' },
    { id: 'kodumudi', name: 'கொடுமுடி', nameEn: 'Kodumudi' },
    { id: 'nambiyur', name: 'நம்பியூர்', nameEn: 'Nambiyur' },
    { id: 'anthiyur', name: 'ஆண்டியூர்', nameEn: 'Anthiyur' },
    { id: 'thalavadi', name: 'தளவாடி', nameEn: 'Thalavadi' },
    { id: 'ammapet', name: 'அம்மாபேட்டை', nameEn: 'Ammapet' },
    { id: 'bhavanisagar', name: 'பவானிசாகர்', nameEn: 'Bhavanisagar' },
    { id: 'chennimalai', name: 'சென்னிமலை', nameEn: 'Chennimalai' },
    { id: 'burgur', name: 'பர்கூர்', nameEn: 'Burgur' },
  ],
  kallakurichi: [
    { id: 'kallakurichi', name: 'கள்ளக்குறிச்சி', nameEn: 'Kallakurichi' },
    { id: 'ulundurpet', name: 'உளுந்தூர்பேட்டை', nameEn: 'Ulundurpet' },
    { id: 'sankarapuram', name: 'சங்கராபுரம்', nameEn: 'Sankarapuram' },
    { id: 'chinnasalem', name: 'சின்னசேலம்', nameEn: 'Chinnasalem' },
    { id: 'kalrayan_hills', name: 'கல்ராயன் மலை', nameEn: 'Kalrayan Hills' },
    { id: 'tirukoilur', name: 'திருக்கோயிலூர்', nameEn: 'Tirukoilur' },
    { id: 'rishivandiyam', name: 'ரிஷிவந்தியம்', nameEn: 'Rishivandiyam' },
    { id: 'thirunavalur', name: 'திருநாவலூர்', nameEn: 'Thirunavalur' },
    { id: 'manalurpet', name: 'மணலூர்பேட்டை', nameEn: 'Manalurpet' },
  ],
  kancheepuram: [
    { id: 'kancheepuram', name: 'காஞ்சிபுரம்', nameEn: 'Kancheepuram' },
    { id: 'uthiramerur', name: 'உத்திரமேரூர்', nameEn: 'Uthiramerur' },
    { id: 'walajabad', name: 'வாலாஜாபாத்', nameEn: 'Walajabad' },
    { id: 'sriperumbudur', name: 'ஸ்ரீபெரும்புதூர்', nameEn: 'Sriperumbudur' },
    { id: 'kundrathur', name: 'குன்றத்தூர்', nameEn: 'Kundrathur' },
    { id: 'st_thomas_mount', name: 'புனித தாமஸ் மலை', nameEn: 'St. Thomas Mount' },
    { id: 'alandur', name: 'ஆலந்தூர்', nameEn: 'Alandur' },
    { id: 'cheyyur', name: 'செய்யூர்', nameEn: 'Cheyyur' },
  ],
  kanyakumari: [
    { id: 'nagercoil', name: 'நாகர்கோவில்', nameEn: 'Nagercoil' },
    { id: 'thovalai', name: 'தோவாளை', nameEn: 'Thovalai' },
    { id: 'agastheeswaram', name: 'அகஸ்தீஸ்வரம்', nameEn: 'Agastheeswaram' },
    { id: 'rajakkamangalam', name: 'ராஜாக்கமங்கலம்', nameEn: 'Rajakkamangalam' },
    { id: 'kurunthancode', name: 'குருந்தன்கோடு', nameEn: 'Kurunthancode' },
    { id: 'killiyoor', name: 'கிள்ளியூர்', nameEn: 'Killiyoor' },
    { id: 'thiruvattar', name: 'திருவட்டார்', nameEn: 'Thiruvattar' },
    { id: 'melpuram', name: 'மேல்புரம்', nameEn: 'Melpuram' },
    { id: 'munchirai', name: 'முஞ்சிறை', nameEn: 'Munchirai' },
  ],
  karur: [
    { id: 'karur', name: 'கரூர்', nameEn: 'Karur' },
    { id: 'kulithalai', name: 'குளித்தலை', nameEn: 'Kulithalai' },
    { id: 'krishnarayapuram', name: 'கிருஷ்ணராயபுரம்', nameEn: 'Krishnarayapuram' },
    { id: 'kadavur', name: 'கடவூர்', nameEn: 'Kadavur' },
    { id: 'aravakurichi', name: 'அரவக்குறிச்சி', nameEn: 'Aravakurichi' },
    { id: 'thanthonimalai', name: 'தந்தோணிமலை', nameEn: 'Thanthonimalai' },
    { id: 'thogamalai', name: 'தோகைமலை', nameEn: 'Thogamalai' },
    { id: 'manmangalam', name: 'மண்மங்கலம்', nameEn: 'Manmangalam' },
  ],
  krishnagiri: [
    { id: 'krishnagiri', name: 'கிருஷ்ணகிரி', nameEn: 'Krishnagiri' },
    { id: 'hosur', name: 'ஓசூர்', nameEn: 'Hosur' },
    { id: 'denkanikottai', name: 'தேன்கனிக்கோட்டை', nameEn: 'Denkanikottai' },
    { id: 'uthangarai', name: 'உத்தங்கரை', nameEn: 'Uthangarai' },
    { id: 'pochampalli', name: 'போச்சம்பள்ளி', nameEn: 'Pochampalli' },
    { id: 'bargur', name: 'பர்கூர்', nameEn: 'Bargur' },
    { id: 'mathur', name: 'மதூர்', nameEn: 'Mathur' },
    { id: 'kaveripattinam', name: 'காவேரிப்பட்டினம்', nameEn: 'Kaveripattinam' },
    { id: 'shoolagiri', name: 'சூளகிரி', nameEn: 'Shoolagiri' },
    { id: 'thally', name: 'தள்ளி', nameEn: 'Thally' },
  ],
  madurai: [
    { id: 'madurai_east', name: 'மதுரை கிழக்கு', nameEn: 'Madurai East' },
    { id: 'madurai_west', name: 'மதுரை மேற்கு', nameEn: 'Madurai West' },
    { id: 'thiruparankundram', name: 'திருப்பரங்குன்றம்', nameEn: 'Thiruparankundram' },
    { id: 'melur', name: 'மேலூர்', nameEn: 'Melur' },
    { id: 'vadipatti', name: 'வாடிப்பட்டி', nameEn: 'Vadipatti' },
    { id: 'usilampatti', name: 'உசிலம்பட்டி', nameEn: 'Usilampatti' },
    { id: 'peraiyur', name: 'பெரையூர்', nameEn: 'Peraiyur' },
    { id: 'thirumangalam', name: 'திருமங்கலம்', nameEn: 'Thirumangalam' },
    { id: 'kallikudi', name: 'கள்ளிக்குடி', nameEn: 'Kallikudi' },
    { id: 'sedapatti', name: 'சேடப்பட்டி', nameEn: 'Sedapatti' },
    { id: 'kottampatti', name: 'கொட்டம்பட்டி', nameEn: 'Kottampatti' },
    { id: 'alanganallur', name: 'அலங்காநல்லூர்', nameEn: 'Alanganallur' },
  ],
  mayiladuthurai: [
    { id: 'mayiladuthurai', name: 'மயிலாடுதுறை', nameEn: 'Mayiladuthurai' },
    { id: 'sirkazhi', name: 'சீர்காழி', nameEn: 'Sirkazhi' },
    { id: 'tharangambadi', name: 'தரங்கம்பாடி', nameEn: 'Tharangambadi' },
    { id: 'kollidam', name: 'கொள்ளிடம்', nameEn: 'Kollidam' },
    { id: 'kuthalam', name: 'குத்தாலம்', nameEn: 'Kuthalam' },
    { id: 'sembanarkoil', name: 'செம்பனார்கோயில்', nameEn: 'Sembanarkoil' },
    { id: 'poompuhar', name: 'பூம்புகார்', nameEn: 'Poompuhar' },
  ],
  nagapattinam: [
    { id: 'nagapattinam', name: 'நாகப்பட்டினம்', nameEn: 'Nagapattinam' },
    { id: 'kilvelur', name: 'கீழ்வேளூர்', nameEn: 'Kilvelur' },
    { id: 'thirukkuvalai', name: 'திருக்குவளை', nameEn: 'Thirukkuvalai' },
    { id: 'vedaranyam', name: 'வேதாரண்யம்', nameEn: 'Vedaranyam' },
    { id: 'thalainayar', name: 'தலைநாயர்', nameEn: 'Thalainayar' },
    { id: 'keelaiyur', name: 'கீழையூர்', nameEn: 'Keelaiyur' },
    { id: 'thiruvengadu', name: 'திருவேங்கடு', nameEn: 'Thiruvengadu' },
  ],
  namakkal: [
    { id: 'namakkal', name: 'நாமக்கல்', nameEn: 'Namakkal' },
    { id: 'rasipuram', name: 'ராசிபுரம்', nameEn: 'Rasipuram' },
    { id: 'tiruchengode', name: 'திருச்செங்கோடு', nameEn: 'Tiruchengode' },
    { id: 'paramathi', name: 'பரமத்தி', nameEn: 'Paramathi' },
    { id: 'velur', name: 'வேலூர்', nameEn: 'Velur' },
    { id: 'mohanur', name: 'மோகனூர்', nameEn: 'Mohanur' },
    { id: 'elachipalayam', name: 'இலாச்சிப்பாளையம்', nameEn: 'Elachipalayam' },
    { id: 'erumapatti', name: 'எருமப்பட்டி', nameEn: 'Erumapatti' },
    { id: 'kolli_hills', name: 'கொல்லி மலை', nameEn: 'Kolli Hills' },
    { id: 'sendamangalam', name: 'சேந்தமங்கலம்', nameEn: 'Sendamangalam' },
    { id: 'namagiripet', name: 'நாமகிரிப்பேட்டை', nameEn: 'Namagiripet' },
    { id: 'komarapalayam', name: 'கொமாரபாளையம்', nameEn: 'Komarapalayam' },
    { id: 'mallasamudram', name: 'மல்லசமுத்திரம்', nameEn: 'Mallasamudram' },
    { id: 'puduchatram', name: 'புதுச்சத்திரம்', nameEn: 'Puduchatram' },
  ],
  nilgiris: [
    { id: 'udhagamandalam', name: 'உதகமண்டலம்', nameEn: 'Udhagamandalam' },
    { id: 'coonoor', name: 'குன்னூர்', nameEn: 'Coonoor' },
    { id: 'kotagiri', name: 'கோத்தகிரி', nameEn: 'Kotagiri' },
    { id: 'gudalur', name: 'குடலூர்', nameEn: 'Gudalur' },
  ],
  perambalur: [
    { id: 'perambalur', name: 'பெரம்பலூர்', nameEn: 'Perambalur' },
    { id: 'veppanthattai', name: 'வேப்பந்தட்டை', nameEn: 'Veppanthattai' },
    { id: 'alathur', name: 'ஆலத்தூர்', nameEn: 'Alathur' },
    { id: 'kunnam', name: 'குன்னம்', nameEn: 'Kunnam' },
  ],
  pudukkottai: [
    { id: 'pudukkottai', name: 'புதுக்கோட்டை', nameEn: 'Pudukkottai' },
    { id: 'alangudi', name: 'ஆலங்குடி', nameEn: 'Alangudi' },
    { id: 'aranthangi', name: 'அறந்தாங்கி', nameEn: 'Aranthangi' },
    { id: 'avudaiyarkoil', name: 'அவுடையார்கோயில்', nameEn: 'Avudaiyarkoil' },
    { id: 'gandarvakottai', name: 'கந்தர்வக்கோட்டை', nameEn: 'Gandarvakottai' },
    { id: 'karambakudi', name: 'காரம்பக்குடி', nameEn: 'Karambakudi' },
    { id: 'kulathur', name: 'குளத்தூர்', nameEn: 'Kulathur' },
    { id: 'manamelkudi', name: 'மனமேல்குடி', nameEn: 'Manamelkudi' },
    { id: 'ponnamaravathi', name: 'பொன்னமராவதி', nameEn: 'Ponnamaravathi' },
    { id: 'thiruvarankulam', name: 'திருவரங்குளம்', nameEn: 'Thiruvarankulam' },
    { id: 'thirumayam', name: 'திருமயம்', nameEn: 'Thirumayam' },
    { id: 'viralimalai', name: 'விராலிமலை', nameEn: 'Viralimalai' },
    { id: 'annavasal', name: 'அன்னவாசல்', nameEn: 'Annavasal' },
  ],
  ramanathapuram: [
    { id: 'ramanathapuram', name: 'ராமநாதபுரம்', nameEn: 'Ramanathapuram' },
    { id: 'paramakudi', name: 'பரமக்குடி', nameEn: 'Paramakudi' },
    { id: 'rameswaram', name: 'ராமேஸ்வரம்', nameEn: 'Rameswaram' },
    { id: 'thiruvadanai', name: 'திருவாடானை', nameEn: 'Thiruvadanai' },
    { id: 'mudukulathur', name: 'முதுகுளத்தூர்', nameEn: 'Mudukulathur' },
    { id: 'kadaladi', name: 'கடலாடி', nameEn: 'Kadaladi' },
    { id: 'nainarkoil', name: 'நயினார்கோயில்', nameEn: 'Nainarkoil' },
    { id: 'bogalur', name: 'போகலூர்', nameEn: 'Bogalur' },
    { id: 'kamuthi', name: 'காமுதி', nameEn: 'Kamuthi' },
    { id: 'rs_mangalam', name: 'ஆர்.எஸ்.மங்கலம்', nameEn: 'R.S.Mangalam' },
    { id: 'mandapam', name: 'மண்டபம்', nameEn: 'Mandapam' },
  ],
  ranipet: [
    { id: 'ranipet', name: 'ராணிப்பேட்டை', nameEn: 'Ranipet' },
    { id: 'arakkonam', name: 'அரக்கோணம்', nameEn: 'Arakkonam' },
    { id: 'walajah', name: 'வாலாஜா', nameEn: 'Walajah' },
    { id: 'arcot', name: 'ஆற்காடு', nameEn: 'Arcot' },
    { id: 'kalavai', name: 'காளவை', nameEn: 'Kalavai' },
    { id: 'nemili', name: 'நெமிலி', nameEn: 'Nemili' },
    { id: 'sholingur', name: 'சோளிங்கர்', nameEn: 'Sholingur' },
    { id: 'timiri', name: 'திமிரி', nameEn: 'Timiri' },
  ],
  salem: [
    { id: 'salem', name: 'சேலம்', nameEn: 'Salem' },
    { id: 'attur', name: 'ஆத்தூர்', nameEn: 'Attur' },
    { id: 'mettur', name: 'மேட்டூர்', nameEn: 'Mettur' },
    { id: 'omalur', name: 'ஓமலூர்', nameEn: 'Omalur' },
    { id: 'gangavalli', name: 'கங்கவள்ளி', nameEn: 'Gangavalli' },
    { id: 'vazhapadi', name: 'வாழப்பாடி', nameEn: 'Vazhapadi' },
    { id: 'yercaud', name: 'ஏற்காடு', nameEn: 'Yercaud' },
    { id: 'edappadi', name: 'ஏடப்பாடி', nameEn: 'Edappadi' },
    { id: 'konganapuram', name: 'கொங்கணாபுரம்', nameEn: 'Konganapuram' },
    { id: 'sankari', name: 'சங்ககிரி', nameEn: 'Sankari' },
    { id: 'thalaivasal', name: 'தலைவாசல்', nameEn: 'Thalaivasal' },
    { id: 'peddanaickenpalayam', name: 'பெத்தநாயக்கன்பாளையம்', nameEn: 'Peddanaickenpalayam' },
    { id: 'ayothiapattinam', name: 'அயோத்தியாப்பட்டினம்', nameEn: 'Ayothiapattinam' },
    { id: 'veerapandi', name: 'வீரபாண்டி', nameEn: 'Veerapandi' },
    { id: 'nangavalli', name: 'நாங்கவள்ளி', nameEn: 'Nangavalli' },
    { id: 'kadayampatti', name: 'கடையம்பட்டி', nameEn: 'Kadayampatti' },
    { id: 'magudanchavadi', name: 'மகுடஞ்சாவடி', nameEn: 'Magudanchavadi' },
    { id: 'kolathur', name: 'கொளத்தூர்', nameEn: 'Kolathur' },
  ],
  sivaganga: [
    { id: 'sivaganga', name: 'சிவகங்கை', nameEn: 'Sivaganga' },
    { id: 'karaikudi', name: 'காரைக்குடி', nameEn: 'Karaikudi' },
    { id: 'devakottai', name: 'தேவகோட்டை', nameEn: 'Devakottai' },
    { id: 'ilayangudi', name: 'இளையான்குடி', nameEn: 'Ilayangudi' },
    { id: 'thiruppuvanam', name: 'திருப்புவனம்', nameEn: 'Thiruppuvanam' },
    { id: 'manamadurai', name: 'மானாமதுரை', nameEn: 'Manamadurai' },
    { id: 'kallal', name: 'கல்லல்', nameEn: 'Kallal' },
    { id: 'singampunari', name: 'சிங்கம்புணரி', nameEn: 'Singampunari' },
    { id: 'sakkottai', name: 'சாக்கோட்டை', nameEn: 'Sakkottai' },
    { id: 'kalayarkovil', name: 'காளையார்கோவில்', nameEn: 'Kalayarkovil' },
    { id: 's_pudur', name: 'எஸ்.புதூர்', nameEn: 'S.Pudur' },
    { id: 'kannangudi', name: 'கண்ணங்குடி', nameEn: 'Kannangudi' },
  ],
  tenkasi: [
    { id: 'tenkasi', name: 'தென்காசி', nameEn: 'Tenkasi' },
    { id: 'sankarankovil', name: 'சங்கரன்கோவில்', nameEn: 'Sankarankovil' },
    { id: 'kadayanallur', name: 'கடையநல்லூர்', nameEn: 'Kadayanallur' },
    { id: 'shenkottai', name: 'செங்கோட்டை', nameEn: 'Shenkottai' },
    { id: 'alangulam', name: 'ஆலங்குளம்', nameEn: 'Alangulam' },
    { id: 'veerakeralampudur', name: 'வீரகேரளம்புதூர்', nameEn: 'Veerakeralampudur' },
    { id: 'kuruvikulam', name: 'குருவிக்குளம்', nameEn: 'Kuruvikulam' },
    { id: 'vasudevanallur', name: 'வாசுதேவநல்லூர்', nameEn: 'Vasudevanallur' },
    { id: 'melaneelithanallur', name: 'மேலநீலிதநல்லூர்', nameEn: 'Melaneelithanallur' },
    { id: 'kadayam', name: 'கடயம்', nameEn: 'Kadayam' },
    { id: 'surandai', name: 'சுரண்டை', nameEn: 'Surandai' },
  ],
  thanjavur: [
    { id: 'thanjavur', name: 'தஞ்சாவூர்', nameEn: 'Thanjavur' },
    { id: 'kumbakonam', name: 'கும்பகோணம்', nameEn: 'Kumbakonam' },
    { id: 'papanasam', name: 'பாபநாசம்', nameEn: 'Papanasam' },
    { id: 'thiruvaiyaru', name: 'திருவையாறு', nameEn: 'Thiruvaiyaru' },
    { id: 'thiruvidaimarudur', name: 'திருவிடைமருதூர்', nameEn: 'Thiruvidaimarudur' },
    { id: 'orathanadu', name: 'ஓரத்தநாடு', nameEn: 'Orathanadu' },
    { id: 'pattukkottai', name: 'பட்டுக்கோட்டை', nameEn: 'Pattukkottai' },
    { id: 'peravurani', name: 'பேராவூரணி', nameEn: 'Peravurani' },
    { id: 'sethubavachatram', name: 'சேதுபாவாசத்திரம்', nameEn: 'Sethubavachatram' },
    { id: 'thiruvonam', name: 'திருவோணம்', nameEn: 'Thiruvonam' },
    { id: 'budalur', name: 'புதலூர்', nameEn: 'Budalur' },
    { id: 'ammapettai', name: 'அம்மாபேட்டை', nameEn: 'Ammapettai' },
    { id: 'madukkur', name: 'மடுக்கூர்', nameEn: 'Madukkur' },
    { id: 'swamimalai', name: 'சுவாமிமலை', nameEn: 'Swamimalai' },
  ],
  theni: [
    { id: 'theni', name: 'தேனி', nameEn: 'Theni' },
    { id: 'periyakulam', name: 'பெரியகுளம்', nameEn: 'Periyakulam' },
    { id: 'andipatti', name: 'ஆண்டிபட்டி', nameEn: 'Andipatti' },
    { id: 'bodinayakkanur', name: 'போடிநாயக்கனூர்', nameEn: 'Bodinayakkanur' },
    { id: 'uthamapalayam', name: 'உத்தமபாளையம்', nameEn: 'Uthamapalayam' },
    { id: 'cumbum', name: 'கம்பம்', nameEn: 'Cumbum' },
    { id: 'chinnamanur', name: 'சின்னமனூர்', nameEn: 'Chinnamanur' },
    { id: 'myladumparai', name: 'மைலாடும்பாறை', nameEn: 'Myladumparai' },
  ],
  thoothukudi: [
    { id: 'thoothukudi', name: 'தூத்துக்குடி', nameEn: 'Thoothukudi' },
    { id: 'kovilpatti', name: 'கோவில்பட்டி', nameEn: 'Kovilpatti' },
    { id: 'ettayapuram', name: 'எட்டயபுரம்', nameEn: 'Ettayapuram' },
    { id: 'tiruchendur', name: 'திருச்செந்தூர்', nameEn: 'Tiruchendur' },
    { id: 'sathankulam', name: 'சாத்தான்குளம்', nameEn: 'Sathankulam' },
    { id: 'srivaikundam', name: 'ஸ்ரீவைகுண்டம்', nameEn: 'Srivaikundam' },
    { id: 'ottapidaram', name: 'ஒட்டப்பிடாரம்', nameEn: 'Ottapidaram' },
    { id: 'kayathar', name: 'காயத்தார்', nameEn: 'Kayathar' },
    { id: 'vilathikulam', name: 'விளாத்திக்குளம்', nameEn: 'Vilathikulam' },
    { id: 'pudur', name: 'புதூர்', nameEn: 'Pudur' },
    { id: 'kalugumalai', name: 'கழுகுமலை', nameEn: 'Kalugumalai' },
    { id: 'udangudi', name: 'உடன்குடி', nameEn: 'Udangudi' },
  ],
  tiruchirappalli: [
    { id: 'trichy_west', name: 'திருச்சி மேற்கு', nameEn: 'Trichy West' },
    { id: 'trichy_east', name: 'திருச்சி கிழக்கு', nameEn: 'Trichy East' },
    { id: 'srirangam', name: 'ஸ்ரீரங்கம்', nameEn: 'Srirangam' },
    { id: 'lalgudi', name: 'லால்குடி', nameEn: 'Lalgudi' },
    { id: 'pullambadi', name: 'புல்லம்பாடி', nameEn: 'Pullambadi' },
    { id: 'musiri', name: 'முசிறி', nameEn: 'Musiri' },
    { id: 'thottiyam', name: 'தொட்டியம்', nameEn: 'Thottiyam' },
    { id: 'thuraiyur', name: 'துறையூர்', nameEn: 'Thuraiyur' },
    { id: 'manachanallur', name: 'மணச்சநல்லூர்', nameEn: 'Manachanallur' },
    { id: 'manikandam', name: 'மணிகண்டம்', nameEn: 'Manikandam' },
    { id: 'andanallur', name: 'ஆண்டநல்லூர்', nameEn: 'Andanallur' },
    { id: 'marungapuri', name: 'மருங்காபுரி', nameEn: 'Marungapuri' },
  ],
  tirunelveli: [
    { id: 'tirunelveli', name: 'திருநெல்வேலி', nameEn: 'Tirunelveli' },
    { id: 'palayamkottai', name: 'பாளையங்கோட்டை', nameEn: 'Palayamkottai' },
    { id: 'ambasamudram', name: 'அம்பாசமுத்திரம்', nameEn: 'Ambasamudram' },
    { id: 'cheranmahadevi', name: 'சேரன்மகாதேவி', nameEn: 'Cheranmahadevi' },
    { id: 'nanguneri', name: 'நாங்குநேரி', nameEn: 'Nanguneri' },
    { id: 'radhapuram', name: 'ராதாபுரம்', nameEn: 'Radhapuram' },
    { id: 'thisayanvilai', name: 'திசையன்விளை', nameEn: 'Thisayanvilai' },
    { id: 'manur', name: 'மானூர்', nameEn: 'Manur' },
    { id: 'vikramasingapuram', name: 'விக்கிரமசிங்கபுரம்', nameEn: 'Vikramasingapuram' },
    { id: 'kalakkad', name: 'கலக்காடு', nameEn: 'Kalakkad' },
    { id: 'pappakudi', name: 'பாப்பாகுடி', nameEn: 'Pappakudi' },
    { id: 'gangaikondan', name: 'கங்கைகொண்டான்', nameEn: 'Gangaikondan' },
  ],
  tirupathur: [
    { id: 'tirupathur', name: 'திருப்பத்தூர்', nameEn: 'Tirupathur' },
    { id: 'vaniyambadi', name: 'வாணியம்பாடி', nameEn: 'Vaniyambadi' },
    { id: 'ambur', name: 'ஆம்பூர்', nameEn: 'Ambur' },
    { id: 'natrampalli', name: 'நாட்றாம்பள்ளி', nameEn: 'Natrampalli' },
    { id: 'alangayam', name: 'ஆலங்காயம்', nameEn: 'Alangayam' },
    { id: 'jolarpet', name: 'ஜோலார்பேட்டை', nameEn: 'Jolarpet' },
    { id: 'kandili', name: 'கண்டிலி', nameEn: 'Kandili' },
    { id: 'madhanur', name: 'மதனூர்', nameEn: 'Madhanur' },
  ],
  tiruppur: [
    { id: 'tiruppur', name: 'திருப்பூர்', nameEn: 'Tiruppur' },
    { id: 'avinashi', name: 'அவினாசி', nameEn: 'Avinashi' },
    { id: 'palladam', name: 'பல்லடம்', nameEn: 'Palladam' },
    { id: 'udumalpet', name: 'உடுமலைப்பேட்டை', nameEn: 'Udumalpet' },
    { id: 'dharapuram', name: 'தாராபுரம்', nameEn: 'Dharapuram' },
    { id: 'kangayam', name: 'காங்கேயம்', nameEn: 'Kangayam' },
    { id: 'madathukulam', name: 'மடத்துக்குளம்', nameEn: 'Madathukulam' },
    { id: 'mulanur', name: 'முளனூர்', nameEn: 'Mulanur' },
    { id: 'pongalur', name: 'பொங்கலூர்', nameEn: 'Pongalur' },
    { id: 'kundadam', name: 'குண்டடம்', nameEn: 'Kundadam' },
    { id: 'vellakoil', name: 'வெள்ளக்கோயில்', nameEn: 'Vellakoil' },
    { id: 'gudimangalam', name: 'குடிமங்கலம்', nameEn: 'Gudimangalam' },
    { id: 'uthukuli', name: 'உத்துக்குளி', nameEn: 'Uthukuli' },
  ],
  tiruvallur: [
    { id: 'tiruvallur', name: 'திருவள்ளூர்', nameEn: 'Tiruvallur' },
    { id: 'ponneri', name: 'பொன்னேரி', nameEn: 'Ponneri' },
    { id: 'gummidipoondi', name: 'கும்மிடிப்பூண்டி', nameEn: 'Gummidipoondi' },
    { id: 'poonamallee', name: 'பூந்தமல்லி', nameEn: 'Poonamallee' },
    { id: 'avadi', name: 'ஆவடி', nameEn: 'Avadi' },
    { id: 'ambattur', name: 'அம்பத்தூர்', nameEn: 'Ambattur' },
    { id: 'madhavaram', name: 'மாதவரம்', nameEn: 'Madhavaram' },
    { id: 'red_hills', name: 'செங்குன்றம்', nameEn: 'Red Hills' },
    { id: 'tiruttani', name: 'திருத்தணி', nameEn: 'Tiruttani' },
    { id: 'ellapuram', name: 'எல்லாபுரம்', nameEn: 'Ellapuram' },
    { id: 'kadambathur', name: 'கடம்பத்தூர்', nameEn: 'Kadambathur' },
    { id: 'pallipet', name: 'பள்ளிப்பேட்', nameEn: 'Pallipet' },
    { id: 'villivakkam', name: 'வில்லிவாக்கம்', nameEn: 'Villivakkam' },
    { id: 'thiruninravur', name: 'திருநின்றவூர்', nameEn: 'Thiruninravur' },
  ],
  tiruvannamalai: [
    { id: 'tiruvannamalai', name: 'திருவண்ணாமலை', nameEn: 'Tiruvannamalai' },
    { id: 'polur', name: 'போளூர்', nameEn: 'Polur' },
    { id: 'arani', name: 'ஆரணி', nameEn: 'Arani' },
    { id: 'chengam', name: 'செங்கம்', nameEn: 'Chengam' },
    { id: 'cheyyar', name: 'செய்யார்', nameEn: 'Cheyyar' },
    { id: 'vandavasi', name: 'வந்தவாசி', nameEn: 'Vandavasi' },
    { id: 'kalasapakkam', name: 'கலசப்பாக்கம்', nameEn: 'Kalasapakkam' },
    { id: 'chetpet', name: 'செட்பேட்', nameEn: 'Chetpet' },
    { id: 'thurinjapuram', name: 'துரிஞ்சபுரம்', nameEn: 'Thurinjapuram' },
    { id: 'thellar', name: 'தெல்லார்', nameEn: 'Thellar' },
    { id: 'vembakkam', name: 'வெம்பாக்கம்', nameEn: 'Vembakkam' },
    { id: 'kilpennathur', name: 'கீழ்பென்னாத்தூர்', nameEn: 'Kilpennathur' },
    { id: 'pernampattu', name: 'பேர்ணம்பட்டு', nameEn: 'Pernampattu' },
    { id: 'jawadhu_hills', name: 'ஜவ்வாது மலை', nameEn: 'Jawadhu Hills' },
    { id: 'anakkavur', name: 'அனக்காவூர்', nameEn: 'Anakkavur' },
    { id: 'west_arani', name: 'மேற்கு ஆரணி', nameEn: 'West Arani' },
    { id: 'thandarampet', name: 'தண்டராம்பட்டு', nameEn: 'Thandarampet' },
  ],
  tiruvarur: [
    { id: 'tiruvarur', name: 'திருவாரூர்', nameEn: 'Tiruvarur' },
    { id: 'mannargudi', name: 'மன்னார்குடி', nameEn: 'Mannargudi' },
    { id: 'nannilam', name: 'நன்னிலம்', nameEn: 'Nannilam' },
    { id: 'needamangalam', name: 'நீடாமங்கலம்', nameEn: 'Needamangalam' },
    { id: 'thiruthuraipoondi', name: 'திருத்துறைப்பூண்டி', nameEn: 'Thiruthuraipoondi' },
    { id: 'valangaiman', name: 'வலங்கைமான்', nameEn: 'Valangaiman' },
    { id: 'kodavasal', name: 'கோடவாசல்', nameEn: 'Kodavasal' },
    { id: 'koradacheri', name: 'கொரடாச்சேரி', nameEn: 'Koradacheri' },
    { id: 'kottur', name: 'கொத்தூர்', nameEn: 'Kottur' },
    { id: 'muthupet', name: 'முத்துப்பேட்டை', nameEn: 'Muthupet' },
  ],
  vellore: [
    { id: 'vellore', name: 'வேலூர்', nameEn: 'Vellore' },
    { id: 'gudiyattam', name: 'குடியாத்தம்', nameEn: 'Gudiyattam' },
    { id: 'katpadi', name: 'காட்பாடி', nameEn: 'Katpadi' },
    { id: 'anaicut', name: 'ஆணைக்கட்டு', nameEn: 'Anaicut' },
    { id: 'kv_kuppam', name: 'கே.வி.குப்பம்', nameEn: 'K.V.Kuppam' },
    { id: 'kaniyambadi', name: 'கணியம்பாடி', nameEn: 'Kaniyambadi' },
    { id: 'pernambut', name: 'பேர்ணாம்பட்டு', nameEn: 'Pernambut' },
    { id: 'kaveripakkam', name: 'காவேரிபாக்கம்', nameEn: 'Kaveripakkam' },
  ],
  viluppuram: [
    { id: 'viluppuram', name: 'விழுப்புரம்', nameEn: 'Viluppuram' },
    { id: 'tindivanam', name: 'திண்டிவனம்', nameEn: 'Tindivanam' },
    { id: 'gingee', name: 'செஞ்சி', nameEn: 'Gingee' },
    { id: 'vanur', name: 'வானூர்', nameEn: 'Vanur' },
    { id: 'marakkanam', name: 'மரக்காணம்', nameEn: 'Marakkanam' },
    { id: 'vikravandi', name: 'விக்கிரவாண்டி', nameEn: 'Vikravandi' },
    { id: 'koliyanur', name: 'கோலியனூர்', nameEn: 'Koliyanur' },
    { id: 'thiruvennainallur', name: 'திருவெண்ணைநல்லூர்', nameEn: 'Thiruvennainallur' },
    { id: 'melmalayanur', name: 'மேல்மலையனூர்', nameEn: 'Melmalayanur' },
    { id: 'mailam', name: 'மயிலம்', nameEn: 'Mailam' },
    { id: 'kandachipuram', name: 'காண்டாச்சிபுரம்', nameEn: 'Kandachipuram' },
    { id: 'mugaiyur', name: 'முகையூர்', nameEn: 'Mugaiyur' },
    { id: 'vallam', name: 'வல்லம்', nameEn: 'Vallam' },
    { id: 'olakkur', name: 'ஒலக்கூர்', nameEn: 'Olakkur' },
    { id: 'kanai', name: 'காணை', nameEn: 'Kanai' },
  ],
  virudhunagar: [
    { id: 'virudhunagar', name: 'விருதுநகர்', nameEn: 'Virudhunagar' },
    { id: 'sivakasi', name: 'சிவகாசி', nameEn: 'Sivakasi' },
    { id: 'srivilliputhur', name: 'ஸ்ரீவில்லிபுத்தூர்', nameEn: 'Srivilliputhur' },
    { id: 'rajapalayam', name: 'ராஜபாளையம்', nameEn: 'Rajapalayam' },
    { id: 'aruppukkottai', name: 'அருப்புக்கோட்டை', nameEn: 'Aruppukkottai' },
    { id: 'tiruchuli', name: 'திருச்சுழி', nameEn: 'Tiruchuli' },
    { id: 'sattur', name: 'சாத்தூர்', nameEn: 'Sattur' },
    { id: 'kariyapatti', name: 'காரியாபட்டி', nameEn: 'Kariyapatti' },
    { id: 'narikudi', name: 'நாரிக்குடி', nameEn: 'Narikudi' },
    { id: 'watrap', name: 'வத்திராயிருப்பு', nameEn: 'Watrap' },
    { id: 'vembakottai', name: 'வெம்பக்கோட்டை', nameEn: 'Vembakottai' },
  ],
};

// Get panchayat unions for a district
export const getPanchayatUnions = (districtId: string) => {
  return PANCHAYAT_UNIONS[districtId] || [];
};
